#!/bin/bash
# Quick ITM Testing Guide for STM32F3 Discovery

echo "ITM Debugging Setup Complete!"
echo ""
echo "=== Step 1: Start OpenOCD (Terminal 1) ==="
echo "openocd -f interface/stlink-v2-1.cfg -f target/stm32f3x.cfg"
echo ""
echo "=== Step 2: Run Firmware (Terminal 2) ==="
echo "cd /home/tandao/Documents/repos/rust_idemy/embedded_rust/embedded\\ project/led-blink"
echo "cargo run --target thumbv7em-none-eabihf"
echo ""
echo "=== Step 3: In GDB Prompt ==="
echo "(gdb) continue"
echo ""
echo "=== Expected Output (in GDB console) ==="
echo "Starting LED patterns..."
echo "Blinking all LEDs..."
echo "Roulette step: LED 0"
echo "Roulette step: LED 1"
echo "..."
echo "Finished 1 roulette cycle."
echo ""
echo "=== Step 4 (Optional): Monitor Raw ITM Log (Terminal 3) ==="
echo "tail -f /tmp/itm.log"
echo ""
echo "=== If No Output Appears ==="
echo "1. Verify OpenOCD is running: ps aux | grep openocd"
echo "2. Check for TPIU errors: openocd -d3 -f interface/stlink-v2-1.cfg -f target/stm32f3x.cfg"
echo "3. Inspect raw ITM capture: od -tx1 /tmp/itm.log | head"
echo "4. See ITM_FIX_SUMMARY.md for troubleshooting"

